version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    working_directory: ~/app
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Install dependencies
          command: |
            echo "No need to install anything. Just build and push the Docker image."

      - run:
          name: Build and push Docker image
          command: |
            echo "Inside the Build and push Docker image step"
            docker --version
            docker build -t sbose5aug/sample-express-app .
            docker tag sbose5aug/sample-express-app sbose5aug/circle_ci_test
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push sbose5aug/circle_ci_test